[package]
name = "config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
env_logger = "*"

[dependencies]
log = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"